### ISSUE TITLE
[question] scss files supported by default?

### ISSUE THREAD

**Issue by minimaldesign** [JaKXz/stylelint-webpack-plugin#118]
This seems to work on `scss` file for me:

```
    new StyleLintPlugin({
      options: {
        context: path.resolve(__dirname, ...),
      },
      lintDirtyModulesOnly: true
    }),
```

<del>But according to the docs, I should have to add `syntax: 'scss'` so I just want to make sure the docs are just out of date and my config is okay.</del> I just RTFMed more carefully… It's getting it from the file extension. I'm still curious about the other one though.

Also wondering why I had to wrap the context into an `options` object to get it to work… The docs seemed to indicate that I should just pass `StyleLintPlugin({ context: ... })` directly 🤔

**Comment by JaKXz** [comment]
@minimaldesign I'm not sure why you have or need an `options` key inside your config object. The [`context` key is used to build up the `files` array](https://github.com/JaKXz/stylelint-webpack-plugin/blob/master/index.js#L16) that goes to the stylelint.lint function.

If you are proposing an API that separates the stylelint options from the StylelintPlugin options, I would be open to a PR for that with a clean implementation, since that would be practicing good safety. ATM, however, you do not need to specify a sub-key for `options` to go to stylelint.

To answer your question, as you saw, scss files should be supported out of the box.

sorry for the slow response!
