### ISSUE TITLE
The line number of the .vue file error message is incorrect

### ISSUE THREAD

**Issue by wenkanglin** [JaKXz/stylelint-webpack-plugin#68]
### version
0.6.0

### webpack config
```
plugins: [
  ...
  new StyleLintPlugin({
      context: dirs.dev, // src
      syntax: 'scss',
      files: ['**/*.css', '**/*.scss', '**/*.vue']
  })
]
```

### what's error
![qq 20170214172626](https://cloud.githubusercontent.com/assets/21100124/22923478/9bafdaa4-f2dc-11e6-9eaa-d6f0ff77475f.png)
the line number of the .vue file error message is incorrect !

**Comment by wenkanglin** [comment]
I use the `stylelint cli` to check the `.vue` file styles, the line number is correct.
![qq 20170214174518](https://cloud.githubusercontent.com/assets/21100124/22923802/d4a4cf80-f2dd-11e6-9694-87df4db76bb0.png)
so, I think the cause the error line number should happen to `style-webpack-plugin`

**Comment by Villae** [comment]
I changed stylelint-processor-html to @mapbox/stylelint-processor-arbitrary-tags as @repsac-by suggested in the vue-loader issue: https://github.com/vuejs/vue-loader/issues/303#issuecomment-282131495

Now I get correct line numbers via stylelint-webpack-plugin.

Also, I reproduced this line number issue directly via stylelint-command (with stylelint-processor-html), when using wildcards in filename:

PS C:\xyz-vuejs-app> stylelint src/**/*.vue --syntax scss
src/components/DevMenu.vue
 **46**:12  ×  Expected "#ffff00" to be "#ff0"   color-hex-length

It works correctly without wildcards:
PS C:\xyz-vuejs-app> stylelint src/components/DevMenu.vue --syntax scss
src/components/DevMenu.vue
 **115**:12  ×  Expected "#ffff00" to be "#ff0"   color-hex-length

115 is the correct line number and that "src/**/*.vue" works fine with @mapbox/stylelint-processor-arbitrary-tags

So, I think that issue is somewhere else than in this webpack-plugin, maybe in stylelint-processor-html :)

**Comment by beeplin** [comment]
+1

**Comment by JaKXz** [comment]
@Villae thank you for your solution. Sounds like this is actually a downstream issue, & that's new. I'm going to close this for now, hopefully more recent versions have helped but feel free to reopen if not.
