### ISSUE TITLE
How to config the module by stylelint-webpack-plugin?

### ISSUE THREAD

**Issue by zhaozhiming** [JaKXz/stylelint-webpack-plugin#83]
Hi, I saw the config of stylelint can write with a module name in node_modules:

```
--config

      Path to a specific configuration file (JSON, YAML, or CommonJS), ** or the
      name of a module in node_modules that points to one **. If no --config
      argument is provided, stylelint will search for configuration files in
      the following places, in this order:
        - a stylelint property in package.json
        - a .stylelintrc file (with or without filename extension:
          .json, .yaml, .yml, and .js are available)
        - a stylelint.config.js file exporting a JS object
      The search will begin in the working directory and move up the directory
      tree until a configuration file is found.
```

So I can do something like this in package.json:  

```
"scripts": {
  "lint": "stylelint src/**/*.css --config stylelint-config-standard"
}
```

[stylelint-config-standard](https://github.com/stylelint/stylelint-config-standard) is a stylelint rules package and I use `npm install` to install to my node_modules folder.  

I use `configFile` of stylelint-webpack-plugin to config the module, but it seems not work.

```js
    new StyleLintPlugin({
      configFile: 'stylelint-config-standard',
      context: 'src',
      files: ['**/*.css'],
    }),
```

My question is: How to config the module by stylelint-webpack-plugin? 
Thanks.

**Comment by JaKXz** [comment]
You would set the `stylelint` block of your `package.json` (or in your `.stylelintrc`) as follows:

```json
{
  "extends": "stylelint-config-standard"
}

**Comment by zhaozhiming** [comment]
Yes, I know I can use the `stylelint` block of my package.json and `.stylelintrc` to do  this.  

But I think the `--config` of `stylelint` not only can point to `stylelint` property in `package.json` or `.stylelintrc`, but also can point to a node_module name. So should the `configFile` in `style-webpack-plugin` have the same ability? If yes, I'm interest to make a PR to do this.

**Comment by JaKXz** [comment]
Thanks for the suggestion, but, unfortunately I think that is beyond the scope of this plugin. This plugin's job is to read the existing config and apply the stylelinter in the webpack build process​. Since stylelint already has a method for resolving and extending configurations, I don't think this plugin needs to reinvent that wheel. That being said, I'm open to reopening this issue if you have something interesting and specific in mind, but to be honest I think your efforts would be better spent working in the cosmiconfig module directly :)
